server:
  port: 8088
spring:
  shardingsphere:
    mode:
      type: Memory   #内存模式
    datasource:
      names: user,order
      user:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.220.128:3301/db_user?allowPublicKeyRetrieval=true
        username: root
        password: bewater
      order:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.220.129:3301/db_order?allowPublicKeyRetrieval=true
        username: root
        password: bewater
    rules:
#      标准分片模式(数据节点模式)
      sharding:
        tables:
          t_user:
            actual-data-nodes: user.t_user    #由数据源名 + 表名组成（参考 Inline 语法规则）
          t_order:
            actual-data-nodes: order.t_order
    props:
      sql-show: true  #	是否在日志中打印 SQL 打印 SQL 可以帮助开发者快速定位系统问题。日志内容包含：逻辑 SQL，真实 SQL 和 SQL 解析结果。 如果开启配置，日志将使用 Topic ShardingSphere-SQL，日志级别是 INFO
